image: node:18

stages:
  - build
  - test
  - deploy
cache:
  paths:
    - node_modules/

variables:
  CI_REGISTRY: registry.git.fhict.nl

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 1 week

test:
  stage: test
  image:
    name: cypress/included:14.3.3
    entrypoint: [""]
  variables:
    PREVIEW_PORT: 5173
  script:
    - npm install
    - npm run build
    - npm run dev &
    - npx wait-on http://localhost:$PREVIEW_PORT --timeout 60000
    - npx cypress run --config-file cypress.config.js --e2e --browser electron --headless

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker compose -f docker-compose.yml down
    - docker compose -f docker-compose.yml up -d --build
    - docker ps
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "DevelopmentBranch"'