image: node:18

stages:
  - build
  - test
  - deploy
cache:
  paths:
    - node_modules/

variables:
  CI_REGISTRY: registry.git.fhict.nl

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 1 week

test:
  stage: test
  image:
    name: cypress/included:14.3.3
    entrypoint: [""]
  variables:
    PREVIEW_PORT: 5173
  script:
    - npm install
    - npm run build
    - npm run dev &
    - npx wait-on http://localhost:$PREVIEW_PORT --timeout 60000
    - npx cypress run --config-file cypress.config.js --e2e --browser electron --headless

deploy:
  stage: deploy
  image: docker:latest
  services:
    - name: docker:dind
      command: ["--host=tcp://0.0.0.0:2375"]
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - apk add --no-cache docker-compose
  script:
    - docker-compose -f docker-compose.local.yml down || true
    - docker-compose -f docker-compose.local.yml up -d --build
  rules:
    - if: '$CI_COMMIT_BRANCH == "DevelopmentBranch"'
  tags:
    - docker