services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: s3-chessplatform_fe:latest
    container_name: chessplatform-frontend
    ports:
      - "5173:5173"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
